FROM golang:latest

ADD . /go/src/github.com/gu-io/gu

WORKDIR /go/src/github.com/gu-io/gu

# Run go get
RUN go get -v -u

# Install gometalinter
RUN go get -u -v github.com/alecthomas/gometalinter

# Install missing lint tools
RUN gometalinter --install

# Run go tests
RUN go test -v ./cmd/...
RUN go test -v ./drivers/...
RUN go test -v ./eventx/...
RUN go test -v ./notifications/...
RUN go test -v ./parsers/...
RUN go test -v ./router/...
RUN go test -v ./shell/...
RUN go test -v ./tests/...
RUN go test -v ./utils/...

# Run go linters
RUN gometalinter --deadline 2m --errors  .
RUN gometalinter --deadline 2m --errors  ./cmd/...
RUN gometalinter --deadline 2m --errors  ./drivers/...
RUN gometalinter --deadline 2m --errors  ./eventx/...
RUN gometalinter --deadline 2m --errors  ./notifications/...
RUN gometalinter --deadline 2m --errors  ./parsers/...
RUN gometalinter --deadline 2m --errors  ./router/...
RUN gometalinter --deadline 2m --errors  ./shell/...
RUN gometalinter --deadline 2m --errors  ./utils/...
