FROM golang:latest

ADD . /go/src/github.com/gu-io/gu

WORKDIR /go/src/github.com/gu-io/gu

# Install gometalinter
RUN go get -u -v github.com/alecthomas/gometalinter

# Install missing lint tools
RUN gometalinter --install

# Run go tests
RUN go test -v ./cmd/...
RUN go test -v ./drivers/...
RUN go test -v ./eventx/...
RUN go test -v ./notifications/...
RUN go test -v ./parsers/...
RUN go test -v ./router/...
RUN go test -v ./shell/...
RUN go test -v ./tests/...
RUN go test -v ./utils/...

# Run go linters
RUN gometalinter --deadline 2m --errors --vendor .
RUN gometalinter --deadline 2m --errors --vendor ./cmd/...
RUN gometalinter --deadline 2m --errors --vendor ./drivers/...
RUN gometalinter --deadline 2m --errors --vendor ./eventx/...
RUN gometalinter --deadline 2m --errors --vendor ./notifications/...
RUN gometalinter --deadline 2m --errors --vendor ./parsers/...
RUN gometalinter --deadline 2m --errors --vendor ./router/...
RUN gometalinter --deadline 2m --errors --vendor ./shell/...
RUN gometalinter --deadline 2m --errors --vendor ./utils/...
